version: '3.6'
services:
  pg:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - /data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432